# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec2a9d858f9f8b95cff7625038d23f6205678e3b243492aea9377cc23eab07912ae8226aeb3301e45166f92d2ffd3df2948967e8421114c7770376d55b425947

test:
  secret_key_base: b6f7fcb435509980194aad8b78eb6f6050f8bc025e4939afaf0e2c71616c296e2d110ae7d96d8b02bc2308faf547cb792c6b337a4806e791b1593fd71f475af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
